### ISSUE TITLE
Save GTLRObject that contains array

### ISSUE THREAD

**Issue by enriquesalas506** [google/google-api-objectivec-client-for-rest#164]
On the wiki says that for saving & retrieving use the following method.
```
NSData *data = [NSData dataWithContentsOfURL:fileURL
                                     options:0
                                       error:&error];
if (data) {
  NSMutableDictionary *dict =
    [NSPropertyListSerialization propertyListWithData:data
                                              options:NSPropertyListMutableContainers
                                               format:NULL
                                                error:&error];
  if (dict) {
    GTLRCalendarQuery_EventsList *eventsList =
      [GTLRCalendarQuery_EventsList objectWithJSON:dict];
  }
}
```

Even when I am saving and retrieving the object in exactly that way, with my own class object, the application crashes and gives me the following output.

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GTLRPostsApi_Profiles profileOfUser]: unrecognized selector sent to instance`

Apparently the client endpoint is not serializing the inner objects inside the array. This wasnt an issue with the RPC Client api. 
**So, how do I save and Retrieve an array with this new Client api??**

**Comment by enriquesalas506** [comment]
I see that there is a Method, objectClassResolver. **Perhaps** that is what I need, can anyone give me a clear example of hot to use it?

**Comment by enriquesalas506** [comment]
Currently I am trying to use [GTLRObject objectWithJSON:dict objectClassResolver:[GTLRObjectClassResolver resolverWithKindMap:[[service class] kindStringToClassMap]], but the problem still persist.

Just as a note, I nsloged kindStringToClassMap and returned me this: 

service classes {
}

**Comment by thomasvl** [comment]
First up, sorry, update the wiki to include both methods for recreating out of JSON (with or without a kind mapping).

Some services vend objects that have a `kind` string property that can be used to identify the type of the object to create.  Not all services do.

If the `kindStringToClassMap` is coming back as an empty dictionary, then it sounds like the api you are trying to use doesn't use those mappings.  So the types of objects to create is done entirely based on the types of the properties on the parent properties in the object graph.

If you do want to use a resolver, you don't have to create one, the `GTLRService` subclass generated or the api will have one exposed in the `objectClassResolver` property.

As far as the exception you are getting, I'm guessing that isn't happening when you attempt to recreate the object from the JSON, but is infact happening some time later when you are trying to access the `profileOfUser` property?  Since we don't really know what your discovery document looks like to say what the data object loos like, it is sorta hard to say exactly what's going wrong.  Is there more details you could share about the service and JSON you are trying to reload?  Failing that, I'd suggest stepping through your code to see when exactly things are throw, and what the actual types of the objects are vs. what you are expecting.  That may help you figure out what you were expecting isn't lining up with what is in the JSON.

**Comment by enriquesalas506** [comment]
I figured out, some files got renamed wrongly doing my migration from rpc to the rest api. thanks
