### ISSUE TITLE
query returns "Cannot determine user location for geographically restricted operation."

### ISSUE THREAD

**Issue by yoasha** [google/google-api-objectivec-client-for-rest#165]
Hi,

I have a customer who is getting "Cannot determine user location for geographically restricted operation." when executing a query using GTLRBooksQuery_VolumesList. I could see that this is mapped to "books.volumes.list" API. I did some googling and found that I'm not alone with this issue... However, I couldn't find a practical solution.

Any suggestion on how to fix or workaround this error?

**Comment by thomasvl** [comment]
Since this library generates code for 100+ apis, we don't always know the ins and outs of every api.  So you might need to follow up with the Books specific api info.  That's maintained by the server teams, and so they will know the details better.

Main docs: [https://developers.google.com/books/](https://developers.google.com/books/)

The docs do mention the need for user location: [UserLocation](https://developers.google.com/books/docs/v1/using#UserLocation).  So it maybe that doing authorized requests and/or providing specific location info might help.

The footer of the books pages have a _Connect_ section with a forum: [Google Books API Forums](https://groups.google.com/a/googleproductforums.com/forum/#!forum/books-api)

**Comment by yoasha** [comment]
Thank you for the speedy reply. Just for your reference, I posted a question on the suggested forum: https://productforums.google.com/forum/#!topic/books-api/e-pQhdxcVpM;context-place=forum/books-api

**Comment by menii** [comment]
did you find any suloution i stuck there too ;(

**Comment by rajbdilip** [comment]
This worked for me.
https://productforums.google.com/forum/#!topic/books-api/cK8VJUhRl9w
