### ISSUE TITLE
How to I get a list of files in a folder?

### ISSUE THREAD

**Issue by jkichline** [google/google-api-objectivec-client-for-rest#166]
The examples on Google Drive API website show that this method should be used:

[GTLRDriveQuery queryForChildrenListWithFolderId:@"FOLDER_ID"]

However, this static method is no longer present and was not marked as deprecated with proper usage rules.  How are we supposed to get a list of files in a folder?

**Comment by thomasvl** [comment]
Not sure what page you are looking at, but maybe it is still talking about the V2 api?  Drive moved to a V3 api a while ago.  The [Notable Changes](https://developers.google.com/drive/v3/web/migration#notable_changes) section of their migration guide mentions:

> * Duplicate and obsolete functionality has been removed. Examples:
>    * The `Children` and `Parents` collections have been removed. Use `files.list` instead.

**Comment by jkichline** [comment]
Thomas:

The page the references this is found here:
https://developers.google.com/drive/v2/reference/children/list#examples

Click on the Objective-C example and you’ll see what I’m referring to.

It wasn’t immediately obvious that I was looking at v2 of the documentation unfortunately.  You may want to better document that on the website, or deprecate the methods in Objective-C instead of just removing the method without instructions on how this should now be performed.

It appears that I should now set the q parameter of the GTLRDriveQuery_FilesList to something like “parents in ‘FOLDER_ID’, is that correct.  This just seems like basic use case stuff that is poorly documented and not found in the v3 of the documentation either: https://developers.google.com/drive/v3/web/folder

**Comment by thomasvl** [comment]
There should be a "V2" in the header of the page just like in the url. Those of us working on the GTLR library don't directly control/work on the per api docs pages, those are usually maintained by the server teams.

There should be a "feedback" link in the top right of the page.  Feedback from developers using the apis will hopefully get a more attention then my filing it.  😄 

BTW - That team seems to support both the v3 and v2 apis, we ship the v3 since it is their preferred, but you could generate v2 and use that if you would rather.

**Comment by thomasvl** [comment]
PS - The folders method is for moving things between folders, etc.  For searching (like your `q` parameter), it looks like you want their [Search docs](https://developers.google.com/drive/v3/web/search-parameters).
