### ISSUE TITLE
Cloud Endpoints timeout and method

### ISSUE THREAD

**Issue by leeweijie** [google/google-api-objectivec-client-for-rest#18]
After generating the client library with the service generator, requests to my cloud endpoints timeout with NSUrlErrorDomain 1001 most of the time. When it doesn't timeout, the client makes a POST request when the rest discovery doc says that its supposed to be a GET request.

Also before this I had to add an exception in app transport security for the appspot.com domain

**Comment by thomasvl** [comment]
Sorry, not completely sure I'm following.

Re transport security - sounds like you might be trying to use http instead of https, I thought all of the end points there supported https.  Is something not set up correctly such that you get https?

What is causing the client to make a POST instead of a GET?  Do you have a lot of arguments so you are going over the URL limits and the client is switching to a POST to ensure the request makes it there?

Can you share any more specific about the discovery doc/etc.  An [http log](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) can be useful to help see what is happening.  You might also need to talk to the cloud endpoints people, for suggestions on what could be the issues server side.

**Comment by leeweijie** [comment]
Hi, thank you for your reply. The issue is solved already though. Turns out I did not include the subdomain for my app transport security exception.
