### ISSUE TITLE
Cocoapod: Unable to satisfy the following requirements for PeopleService

### ISSUE THREAD

**Issue by sonnykr** [google/google-api-objectivec-client-for-rest#197]
I am having issues installing PeopleService pod using this pod file. My minimum deployment target for iOS is set to 9.0. Calendar service is working just fine.

```
platform :ios, '9.0'

use_frameworks!
target 'project-name' do
    pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
    pod 'GoogleAPIClientForREST/PeopleService'
    pod 'Google/SignIn', '~> 3.0.3'
    ...
end
```

The error I am getting:

```
[!] Unable to satisfy the following requirements:

- `GoogleAPIClientForREST/PeopleService` required by `Podfile`

Specs satisfying the `GoogleAPIClientForREST/PeopleService` dependency were found, but they required a higher minimum deployment target.
```

**Comment by thomasvl** [comment]
9.0 should be fine for iOS, my one guess could be the fact that you are sticking a version on `GoogleAPIClientForREST/Calendar`, but not on `GoogleAPIClientForREST/PeopleService` and so it is providing a confusing error because it is trying to use different versions of subspecs that are part of the same pod.  Try setting the version on both and see if that resolves it.
