### ISSUE TITLE
Generate objective c classes without nullable

### ISSUE THREAD

**Issue by OuSS-90** [google/google-api-objectivec-client-for-rest#205]
Before i was able to generate class that have property like @property(nonatomic, copy)
After this update it's like @property(nonatomic, copy, nullable)
Is there a way to generate classes without nullable ??

**Comment by thomasvl** [comment]
I believe this project has always included the `nullable` from the start.  If you are talking about the older one, it might not have gotten added when the nullable annotations where added by objective c, but the properties always were nullable.

**Comment by OuSS-90** [comment]
If i remove nullable from objective c classes, it may cause any problem ??

**Comment by thomasvl** [comment]
I'm assuming you are asking because of wanting to use Swift and don't want them bridged as optionals?  The answer is you will crash if the values aren't there, because they really are optional.  The server might not always provide the fields, a field mask can be used to get subsets, etc.  So swift won't like them not being optional but the Objective C objects not really having values.

**Comment by OuSS-90** [comment]
Yes i'm using swift and with this nullable i need to change all code of my project cause it become optionals :(

**Comment by OuSS-90** [comment]
Before this update, the property was like 
@property(nonatomic, copy) NSString *lastName; ---> I get in swift lastName: String! ( it can be nil )
but now it's like this 
@property(nonatomic, copy, nullable) NSString *lastName; ---->  I get in swift lastName: String?

I tried to remove nullable but when value it's nil i get wrong print like it don't have any value
Is there a way to have non optional in swift but it can have nil value so i can test if == nil

**Comment by OuSS-90** [comment]
I used null_resettable instead of nullable and it work like a want, it's not bad for classes right ?

**Comment by OuSS-90** [comment]
I get also nil when the value it's null

**Comment by thomasvl** [comment]
I'm not completely sure what you are saying/asking.

Apple's docs are a little light: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID45

Some other past discussion: http://nshipster.com/swift-1.2/

But since you won't want things to be optional, I would expect things to error if removed that support from the ObjC headers, and then the object serves up nil at runtime.

**Comment by hordurhauks** [comment]
I second this issue. What if we have a field that should never be null?  If the server isn't providing the value for a field it would be an error and the app should crash. To be more specific, say we have a Dog class like this:

class Dog {
  var identifier:NSNumber!
  var name:String?
}

If the server would give us a dog with no identifier then there's something wrong with the server and it would be normal for the app to crash. Am I missing something here?

**Comment by thomasvl** [comment]
I believe with field masks, anything can be left out in data a client fetches.
