### ISSUE TITLE
How to use GTLRBatchQUery in swift

### ISSUE THREAD

**Issue by MIOSY** [google/google-api-objectivec-client-for-rest#223]
I've msgIDs array of size 20K/20K. i want to fetch full mal using those IDs with Batch Query in swift. Here is my tried code but unsuccessfull takes long time. How can i use Batch QUery in a efficient manner.
    
    func MakingMsgIDBatchesAndFetching() {
        let msgIDBatches = messageIDes.divideBy(by: 100) //Diving array into subArrays of 100 elements. Main Array contains 20K/30K ID's of msgs.
        let batchQuery = GTLRBatchQuery ()
        for subArray in msgIDBatches{
            for message in subArray {
                let query1 = GTLRGmailQuery_UsersMessagesGet.query(withUserId: "me", identifier: message as! String)
                query1.format = kGTLRGmailFormatFull
                batchQuery.addQuery(query1)
            }
        }
        self.service.executeQuery(batchQuery,
                                  delegate: self,
                                  didFinish: #selector(displayMessageDetailsList(ticket:finishedWithObject:error:)))
    }
    @objc func displayMessageDetailsList(ticket : GTLRServiceTicket,
                                         finishedWithObject messageResponse : GTLRBatchResult,
                                         error : NSError?) {
        
        var Messages = messageResponse.successes
    }
    
    extension Array {
        func divideBy(by size: Int) -> [[Element]] {
            return stride(from: 0, to: self.count, by: size).map {
                Array(self[$0..<Swift.min($0 + size, self.count)])
            }
        }
    }

**Comment by thomasvl** [comment]
I don't have much direct experience with the gmail api, so you might want to check their api specific pages to see if they have performance tips, etc.

If I'm following correctly, you are trying to fetch thousands of messages.  That can actually be a case where batching isn't a good thing.

For _small_ operations, the http overhead for each action can be enough, that better performance can be had by sending them in a batch to minimize the overhead per action.

But since you want to fetch full mail messages, each one of these is likely to be pretty large.  That means if any time out happens during transmission you end up getting none of them.  Likewise, if some messages are overly large, you run the risk of the server side work also being so large it forces a timeout.  So for something like this, you might be better off getting individual messages because the _cost_ of each reply is way more than the http overhead.
