### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by simonmeusel** [google/google-api-objectivec-client-for-rest#225]
Since Carthage brings a lot more flexibility, it would be great if this project would support it.

https://github.com/Carthage/Carthage

**Comment by thomasvl** [comment]
I don't know Carthage, but last time I looked, one of the hard parts would be dealing with all the individual services.  For pods, we can automate having the podspec provide all the sub targets, but I didn't see anything like that for Carthage, it seemed like we've have to manually add targets to the project file, and it wasn't clear how someone could depend on just the services they wanted?

Since ObjC doesn't really deadstrip, providing one target with *all* the possible services would mean anyone using Carthage gets a really bloated application, which they probably wouldn't want.

**Comment by dominic-healid** [comment]
Hi,

I'm also using Carthage and I'm also new with iOS Development can you guys give me some pointers on how to use this with my swift project?

I'm trying to add this on my xcode project but I don't get the output framework.

Please help.

**Comment by simonmeusel** [comment]
This projet is not Carthage compatible right now. You probably can only add this project manually, or use a differs package manager, like cocoa pods.

If you wan’t to make calls to the Google APIs and use Carthage, you can make the HTTP requests manually with Alamofire.

**Comment by thomasvl** [comment]
As mentioned, none of us that work on this have experience with Carthage, and I'm not sure how one would support all the different services that can be generated.  Adding them all to a single Xcode project doesn't scale well, and folks wouldn't want to always include all of them as that could lead to a lot of bloat in the application by having all the sources they don't need.

Tagging this with help wanted incase folks with Carthage experience have ideas on how to handle it.

**Comment by thomasvl** [comment]
Closing this out as CocoaPods and SwiftPM seem to the the main things these days and CocoaPods likely to even be on the decline.
