### ISSUE TITLE
Localized error messages

### ISSUE THREAD

**Issue by hugofalkman** [google/google-api-objectivec-client-for-rest#230]
I set GIDSignIn.sharedInstance().language = Locale.current.languageCode and the sign in is totally in the local language. Nice.

But I can't find a way to localize error messages. Neither the GTLRCalendarService() and GTLRPeopleServiceService() nor the query methods of those services have a language property to set so that error.localizedDescription in the completion handler's (ticket, response, error) shows up in the local language.

Am I missing something?

**Comment by hugofalkman** [comment]
For the Calendar API I am talking about these 11 messages https://developers.google.com/calendar/v3/errors
Are they available in localized format?

**Comment by thomasvl** [comment]
I don't know that specific service well, but from a quick scan of those errors, it seems like almost none of them would be directly presented to the user.  It looks like they are documenting error numbers and providing strings purely as an developer tool.  The numbers are likely there for you the developer to then pick off and react accordingly too.  For example:

* _400: Bad Request_ – unless you are providing a UX where the end user crafts the raw query, it is an indication that something has gone wrong in your program, and what you are sending isn't valid.
* _401: Invalid Credentials_ – If you are letting `GIDSignIn` do proper refreshing, the only way this would happen is that something has causing your auth tokens to become invalid (revoked, etc.), and so you'll want to instead message the user about needing to resign in.
* _ 403: * Limit Exceeded_ – Same, the user can't do much, if you have a metrics feedback mechanism, you likely will want to know that your App's quota on console is exhausted, and generally supporting a UX to allow for backoff and ensuring your can't hammer the server with requests is a good thing.
...

So most of these don't really seem like you'd want to display the raw info to the user, but instead realize what is happening and ensure your app responds correctly based on your specific UX.

But to your point of getting some of the text translated, you can try the support areas for that API to see if someone has asked already, or ask yourself to see if they support it or if the intent is like I'm guessing where they are expecting the Apps to provide their proper messaging since most of these issues the end user can't "correct".

**Comment by hugofalkman** [comment]
Ok, point taken.

How can I in my app access the error code to handle some of these errors? It seems the code is part of the API

**Comment by thomasvl** [comment]
> How can I in my app access the error code to handle some of these errors? It seems the code is part of the API but I don't see it in the objc library.

When you [execute your query](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRService.h#L188-L211), the [`completionHandler`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRService.h#L105-L118) can get an `NSError` if things fail. That `NSError` could be a basic Foundation error for networking issues, but if the server returned an one of those error objects, you can use the helper [`+[GTLRErrorObject underlyingObjectForError:]`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRErrorObject.h#L39-L46) to extract what was in the payload.  `GTLRErrorObject` then exposes both the V1 and V2 formats for all their sub data.

**Comment by hugofalkman** [comment]
Thank you for your help.

Can't really read objc code so took me a while to figure out the following Swift code that seems to work:
service.executeQuery(query) { (ticket, response, error) in                
                if let error = error {
                    let code = GTLRErrorObject(foundationError: error).code ?? 0
                    . . .
                }
}

**Comment by thomasvl** [comment]
I believe that's backwards, you are making a new `GTLRErrorObject` out of the foundation error rather then extracting one (if it is there).  I believe it should be bridging like `GTLRErrorObject.underlyingObject(forError: NSError) -> GTLRErrorObject`. So:

```swift
if let error = error {
  if let errObj = GTLRErrorObject.underlyingObject(error) {
    // code using errObj
  } else {
   // code just using error
}
```

**Comment by hugofalkman** [comment]
Yes, thank you that works fine. Strange that making a new GTLRErrorObject also gave the right error code.
