### ISSUE TITLE
Account verification

### ISSUE THREAD

**Issue by DeepaSuhas** [google/google-api-objectivec-client-for-rest#241]
To upload custom thumbnails, you must have a verified account. Is there any API call to check if an account on YouTube verified or not? 

While try to upload custom thumbnails ( if an account on YouTube not verified ) I'm getting this error message
{"error":{"errors":[{"domain":"youtube.thumbnail","reason":"forbidden","message":"The authenticated user doesnt have permissions to upload and set custom video thumbnails.","locationType":"header","location":"Authorization"}],"code":403,"message":"The authenticated user doesnt have permissions to upload and set custom video thumbnails."}}

**Comment by thomasvl** [comment]
Since the library supports so many apis (they generate from the Discovery data), we don't know the ins/outs of each individual one.  I'd suggest reading the docs for the YouTube api to see what exactly is required, but my guess would be it isn't something about this api as much as it is about the account doing the upload.  Assuming you are using GTMAppAuth or GoogleSignIn, what ever account the user plugs in there, would be the one that would have to be an authenticated one, and then the credentials attached to the requests will allow the server to look up the account and confirm it is a verified account.

**Comment by StevenEWright** [comment]
https://stackoverflow.com/questions/20484816/is-there-a-field-for-knowing-if-the-youtube-channel-is-verified-from-the-youtube
