### ISSUE TITLE
How to fetch more pages with out crashing query = GTLRGmailQuery_UsersMessagesList.query(withUserId: "me")

### ISSUE THREAD

**Issue by mattbecker5** [google/google-api-objectivec-client-for-rest#267]
query = GTLRGmailQuery_UsersMessagesList.query(withUserId: "me")
        query.q = "in:all"
        query.maxResults = 1000
        query.executionParameters.shouldFetchNextPages = true
        query.executionParameters.retryEnabled = true

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Fetched too many next pages executing GTLRGmailQuery_UsersMessagesList; increase maxResults page size to avoid this.'

I think I know why this is happing but I can't think of how to fetch more or less but still be able to fetch the entire email box?
It seems that it will fetch up to around 15 pages and only 500 emails per page I believe my email account has many more pages then that and this is causing it to fail.

any thoughts?

**Comment by thomasvl** [comment]
Sorry for the late reply.  For something as big as an people's email, you really don't want to use `shouldFetchNextPages`.  The problem is that forces *everything* into memory.  You should use a large page size, but then manually fetch the chunks yourself using the next page tokens, this way you can process subsets incrementally and never have to have everything in memory at once.
