### ISSUE TITLE
Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup

### ISSUE THREAD

**Issue by Xcdmau5** [google/google-api-objectivec-client-for-rest#281]
Hi. I'm using GoogleAPIClientForREST to access files from Google Drive and download or play (audio files) them. A few days ago it worked great. I've been getting live links to files and and successfully downloaded files. For Authenticate I used GoogleSignIn library.

But today everything stopped working. I'm successful obtain GIDGoogleUser and GTMFetcherAuthorizationProtocol and set it to GTLRDriveService. But when I'm trying to play files or download, then error appears: 
`{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}`

I update all libraries for the lates versions (using pods), but error didn't disappear. 

Then I watched the User Info, which I received after logging and saw, that expirationDate is expired:
`GIDGTMOAuth2AuthenticationWithEMMSupport 0x282b15b80: {accessToken="######", refreshToken="######", expirationDate="2019-04-05 13:51:47 +0000"}`

I tried to create new Application in console.developers.google.com, but error didn't disappear. One more thing is that expirationDate of new account is the same. (Maybe it important :) )

**Comment by thomasvl** [comment]
First up, you likely need to go revoke your tokens for safety sake since you posted the access token and refresh token publicly.

All tokens have an expirations, under the hood, GTMAppAuth or GoogleLogin (or whatever you are using) will use the refresh to get a new token to keep things going.  But that isn't the problem you are likely hitting.

The error you quoted is usageLimits.  Most apis have a limit on how many requests an app or user can make in a given amount of time.  The error you quote says _Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup._ You likely need to read the Drive specific docs to see what their api policies are for the unauthenticated and authenticate access, and figure out what you will need for what ever you are building.  That isn't going to be specific to this library, it is just in their terms for the apis.

**Comment by Xcdmau5** [comment]
Thank you for notification about tokens. 

Firstly, I checked Limits of quotes on developer console.  The limits are more bigger, than count of my requests. 

Also I think, that I receive the token from GoogleSignIn and after that I should fetch the Unauthenticated link of the file. Just cannot understand why my requests are unauthenticated when I installed token to the library.

Also I tried your example app from this repo and it's also give me this error.
<img width="406" alt="Screen Shot 2019-04-05 at 18 14 35" src="https://user-images.githubusercontent.com/26894470/55642737-a46e8a80-57d1-11e9-95b5-ac20471f595b.png">

**Comment by canhductu1980** [comment]
Hoang van canh

**Comment by canhductu1980** [comment]
Hoang van canh

**Comment by canhductu1980** [comment]
Canhductu1980@gmail.com

**Comment by andrewvmail** [comment]
I'm also running into this issue.

**Comment by andrewvmail** [comment]
@Xcdmau5 

I just ran into similar problem and turned out i forgot to setup this screen.
https://console.developers.google.com/apis/credentials/consent

![Screen Shot 2019-06-21 at 1 59 52 AM](https://user-images.githubusercontent.com/2431354/59911258-52003b80-93c8-11e9-9712-039385d9349b.png)

**Comment by thomasvl** [comment]
Closing this out since the limits and setting up tokens will be based on what library you use for auth (GTMAppAuth or GoogleLogin (or something else that vends an object that implements the required protocol)).
