### ISSUE TITLE
testService_testBlock_CallbackQueue flakes off and on

### ISSUE THREAD

**Issue by thomasvl** [google/google-api-objectivec-client-for-rest#29]
Travis status shows this as flaking off an on.  The bug might actually be down in the test server and not in the GTLR code itself.  It would nice to finish nailing this down (and fixing it).

**Comment by thomasvl** [comment]
Actually testService_BatchQuery_Paging also failed [here](https://travis-ci.org/google/google-api-objectivec-client-for-rest/jobs/153356770), could be the same root cause.

**Comment by thomasvl** [comment]
https://github.com/google/google-api-objectivec-client-for-rest/pull/34 should fix one of them, but keeping this open due to the second.

**Comment by sergiocampama** [comment]
I believe the testService_BatchQuery_Paging test has a race condition. This happens because we are setting up 5 expectations at the top of the test, but on line 

https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Tests/GTLRServiceTest.m#L1769

we are waiting for 6 background tasks to be started and finished. If the background tasks for the specified queries, that fullfill the 5 expectations, complete before the extra background task, the [waitForExpectationsWithTimeout:handler:]  will return, and when checking that the number of beginTaskIds is the same as endTaskIds, they will not be the same and the test will fail..

I think this is GTMSessionFetcher calling a background task for something other than the queries, but not sure yet what. The comment just above verifyCountingUIAppWithExpectedCount mentions that there is an extra background task called, but not very useful in explaining what it is.

**Comment by thomasvl** [comment]
Closing this out because the session fetch got some tweaks in the last year also, we'll see if things start happening again.
