### ISSUE TITLE
GTLR framework & GTMFetcher dependency Problem

### ISSUE THREAD

**Issue by SteveDCronin** [google/google-api-objectivec-client-for-rest#291]
I am using the framework as built by this Xcode project and I am also using GMTAppAuth.
The GTMAppAuth is implemented by the Pods mechanism...
Both of these embed the GTMSessionFetcher tools. 

As a result I see 10 messages similar to this in the console when running:
`objc[7259]: Class GTMSessionFetcher is implemented in both /Users/steve/Library/Developer/Xcode/DerivedData/XYZ-gctjkmntzetjecauruecqaicjlqq/Build/Products/Debug/GTLR.framework/Versions/A/GTLR (0x100865210) and /Users/steve/Library/Developer/Xcode/DerivedData/XYZ-gctjkmntzetjecauruecqaicjlqq/Build/Products/Debug/ZYZ.app/Contents/MacOS/XYZ (0x100337188). One of the two will be used. Which one is undefined.`

I am leery about fiddling around with the Pod behavior, so my inclination is the tweak the framework.
If I simply remove the 7 'm' files found in the 'Deps' directory then I get 7 undefined symbol errors when building the framework...
` "_GTMFetcherApplicationIdentifier", referenced from:
      -[GTLRService requestUserAgent] in GTLRService.o
`

What is the best way to retain a single instance of the required GTMFetcher tools?

Steve

**Comment by SteveDCronin** [comment]
So I experimented with the Pod setup for GTMAppAuth.
Basically I modified the Pods-XYZ.debug.xconfig (& release);
changed HEADER_SEARCH_PATHS; LIBRARY_SEARCH_PATHS;OTHER_LDFLAGS by removing the GMTSessionFetcher components. 
I also then removed the GTMSessionFetcher target from the Pods-XYZ target dependencies..

I get a clean build and it clears up the console logging messages regarding duplicate classes...
Is this kosher? Have I created a problem for myself by doing this?

**Comment by thomasvl** [comment]
Mixing Pods from the one case with the checked in project is sorta your own territory and not something we're likely to try and support.

**Comment by SteveDCronin** [comment]
Thomas;

I don't mean this to be snide but the way you have packaged GTMAuth and the Rest tools for Objc makes your comment above equivalent to saying "we are not going to support using GMTAuth with the Rest tools..."

**Comment by thomasvl** [comment]
That wasn't the intent.  We either expect you to use

1. The include Xcode project for this library and the GTMSessionFetcher, but that pull in which other authentication/authorization library you are using via their documented means of their Xcode project or their support for manually adding sources.
1. This project via raw sources and then integration your authentication/authorization library via their documented means.
1. CocoaPods for everything.

You're looking for support hotwiring a few systems together, which I think sorta goes past what most library would be able to support, you are creating a setup that sounds very custom to how you want to do things, which means most of the trouble shooting is going to fall on your end since you will be the only one that really knows how you are trying to make it work.

Since GTLR can take the authentication/authorization support via a protocol, we [document two](https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization) things we know can be used (GTMAppAuth/Google Sign-In), but the library can be used with others.  And we can't really document what would be done for every thing that might use those libraries, so we defer to the other libraries to document some of their integration rather then recreating it.

**Comment by SteveDCronin** [comment]
Ok I get your point!  Thanks for your help here!
