### ISSUE TITLE
Publish library as a Swift package

### ISSUE THREAD

**Issue by LarsStegman** [google/google-api-objectivec-client-for-rest#296]
Hello,

I want to create an app using this library in Swift, but I want to use the [Swift Package Manager](https://github.com/apple/swift-package-manager/tree/master/Documentation) instead of CocoaPods. This requires the package to have a `Package.swift` file in the root directory as the package specification. It's possible to create a Swift package from Objective C code, so this shouldn't be a problem. 

I have tried to create `Package.swift` myself, but it requires the dependencies like `GTMSessionFetcher` to be published as a Swift Package as well. In addition to this `GoogleSignIn` would need to be published as a Swift Package as well if authorised APIs are used.

Would it be possible to do this?

Thanks!

**Comment by thomasvl** [comment]
I've been debating making one, but haven't had the time to play with it yet (figuring out how to model what CocoaPod's subspecs does for all the services is the harder part).  But if you'd like to do a PR (and one on _GTMSessionFetcher_, that would be great.

Note: this package souldn't not directly depend on _GoogleSignIn_ because all the code here needs is the prototocol provided by _GTMSessionFetcher_.  The code a developer writes on top of this would bridge the two, so that is where the dependency on _GoogleSignIn_ (or _GTMAppAuth_) would go.

**Comment by JonasGessner** [comment]
I opened an issue on GTMSessionFetcher to track SPM support there: https://github.com/google/gtm-session-fetcher/issues/157

**Comment by thomasvl** [comment]
Thinking a little more about this, I think SwiftPM might not be able to express things well enough.

The current CocoaPod has lots subspecs: _Core_ and then one for every Service.  The subspecs exist because ObjC doesn't really dead strip, so they allow a developer to pick up the amount needed and not get extra bloat.  From a source POV, since they end up in one module, he `#import` directive work out as they are still a single module name.

While SwiftPM has different products/libraries within a `Package.swift`, they all end up with different names, so the sources would need to know how to differently import the headers to actually build, but since SwiftPM is mainly focused on Swift, there isn't a convention of having some preprocessor symbol one can use for the source to conditionally get the right import.

So for SwiftPM support, it might mean a single library, with **everything**, and given the number of services that are in Google's discovery list, that would likely mean a lot of bloat that developers don't need/want.

It might be worth checking the Swift Forums for any discussion on bringing better support to SwiftPM for things like this; and if there aren't any, opening a thread to discuss it.

**Comment by thomasvl** [comment]
Keeping this open for tracking and to see if folks have ideas, but I do worry about the "all or nothing" part and including every service seems like it could bloat applications unless someone has a good way to model what cocoapods does with the subspecs.

**Comment by thomasvl** [comment]
GTMSessionFetcher got a `Package.swift`.

Thinking about things here some more, it might work if
- A target for the _main_ part of the library, and then a target for every service generated.
- Likely have to tweak the generated sources to have `#if SWIFT_PACKAGE` checks to use `@import` of modules instead.
- Do something like `Source/Tools/update_podspec_services.py` that updates the `Package.swift` to have a target for each service.

Then I think folks could depend on just the core (if they have their own generated service(s), or they could depend on a specific service target from this package.

It might make sense to stage this, say land a `Package.swift` that does the core library & tests,  first.  Then circle back to all the generator changes to expose the services as packages also and then likely the and _ServiceGenerator_ binary also (since it needs _Discovery_).  Although having the ServiceGenerator might be a problem since I believe SwiftPM support is sorta week for saying a target/product is only valid on one platform.

**Comment by karimhm** [comment]
@thomasvl  Does this project have restrictions related to moving source and header files?

**Comment by thomasvl** [comment]
> @thomasvl Does this project have restrictions related to moving source and header files?

Yup, same issues would apply.

**Comment by thomasvl** [comment]
With #351 in, the next thing needed is to update the ServiceGenerator to tweak what it generates to also work with SwiftPM.

I'll look at doing that in the next day or so, I think there likely are two modes need:
- Conditional of `SWIFT_PM` like the core code.
- Force `@import` of the package names.

The first would be for the code checked in here and hence in this `Package.swift`, the second is likely easier for folks directly added sources to their own Xcode project that uses GTLR via Xcode's SwiftPM integration.

**Comment by thomasvl** [comment]
Hm, should we have added a package `GoogleAPIClientForREST` that just wraps the _Core_ one? Or renamed the _Core_ one?  I think we did that over in GTMSessionFetcher, just wondering it would have helped to get module names more aligned between SwiftPM and CocoaPods.

**Comment by karimhm** [comment]
In GTMSessionFetcher, the `GTMSessionFetcher` package is a wrapper around **`GTMSessionFetcherCore`** and **`GTMSessionFetcherFull`**.

Adding a `GoogleAPIClientForREST` package that wraps the _Core_ only seems redundant to me.
Unless it gonna wrap every single package inside (which is a crazy thing).

**Comment by thomasvl** [comment]
Hopefully we shouldn't have done `GoogleAPIClientForRESTCore` -> `GoogleAPIClientForREST` to make things line up any better.  I didn't really consider it for the SessionFetcher either. 😦 I guess we roll with these changes, and see what feedback things get.
