### ISSUE TITLE
send emial subject 中文乱码

### ISSUE THREAD

**Issue by kuangzihui** [google/google-api-objectivec-client-for-rest#314]
发送邮件时标题中文乱码，大神们有解决办法么，感谢了

**Comment by thomasvl** [comment]
I'm not sure if you are asking about something specific to the gmail service api or a more general question not related to this library.

**Comment by kuangzihui** [comment]
- (NSData *)getFormattedRawMessage
{
    // Date string
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
    dateFormatter.dateFormat = @"EEE, dd MMM yyyy HH:mm:ss Z";
    NSString *strDate = [dateFormatter stringFromDate:[NSDate date]];
    NSString *finalDate = [NSString stringWithFormat:@"Date: %@\r\n", strDate];

    // From string
    NSString *from = @"From: <constantin.saulenco@gmail.com>\r\n";

    // To string
    NSString *to = @"To: <constantin.saulenco@mobiversal.com>\r\n";

    // CC string
    NSString *cc = @"";

    // BCC string
    NSString *bcc = @"";

    // Subject string
    NSString *subject = @"Subject: New stuff\r\n\r\n";

    // Body string
    NSString *body = @"Hello my friend, \n can you please call me when have free time. \nMark. \r\n";

    // Final string to be returned
    NSString *rawMessage = @"";

    // Send as "multipart/mixed"
    NSString *contentTypeMain = @"Content-Type: multipart/mixed; boundary=\"project\"\r\n";

    // Reusable Boundary string
    NSString *boundary = @"\r\n--project\r\n";

    // Body string
    NSString *contentTypePlain = @"Content-Type: text/plain; charset=\"UTF-8\"\r\n";

    // Combine strings from "finalDate" to "body"
    rawMessage = [[[[[[[[[contentTypeMain stringByAppendingString:finalDate] stringByAppendingString:from]stringByAppendingString:to]stringByAppendingString:cc]stringByAppendingString:bcc]stringByAppendingString:subject]stringByAppendingString:boundary]stringByAppendingString:contentTypePlain]stringByAppendingString:body];


    // Image Content Type string
    NSString *contentTypeJPG = boundary;
    contentTypeJPG = [contentTypeJPG stringByAppendingString:[NSString stringWithFormat:@"Content-Type: image/jpeg; name=\"%@\"\r\n",@"IMG_1253.jpg"]];
    contentTypeJPG = [contentTypeJPG stringByAppendingString:@"Content-Transfer-Encoding: base64\r\n"];

    // PNG image data
    UIImage *image = [UIImage imageNamed:@"IMG_1253.jpg"];
    NSData *jpegData = UIImageJPEGRepresentation(image, 1);
    NSString *imageBase64String = GTLREncodeBase64(jpegData);
    NSString *pngString = [NSString stringWithFormat:@"%@\r\n",imageBase64String];
    contentTypeJPG = [contentTypeJPG stringByAppendingString:pngString];

    // Add to raw message
    rawMessage = [rawMessage stringByAppendingString:contentTypeJPG];


    // End string
    rawMessage = [rawMessage stringByAppendingString:@"\r\n--project--"];

    return [rawMessage dataUsingEncoding:NSUTF8StringEncoding];
}

**Comment by kuangzihui** [comment]
Subject 中文会产生乱码

**Comment by thomasvl** [comment]
My guess would be this might be less about the server api and more about your actually message payload being generated, but I'm not sure.

This library support 100+ apis, so we don't have much direct experience using the majority of them, so for detailed questions on the Gmail API, you'll likely need to use some of their [documented support methods](https://developers.google.com/gmail/api/support).

On the server support areas, instead of just providing ObjC code snippets, it can sometimes be more useful to just show what the network requests end up looking like (because the folks that might be able to help know the server side and don't always know ObjC). To easily get what is being set out, the library support logging the requests generated: [HTTP Logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic).  So including those should show the final REST request/payload for them.
