### ISSUE TITLE
How to make live broadcast 180 stereo video ?

### ISSUE THREAD

**Issue by vasilok** [google/google-api-objectivec-client-for-rest#317]
I have custom camera which can capture stereo video 180 degrees,  but when i try make live broadcasting throught ios application i get wrong video on site  - full 360 degrees sphere with both eyes on it :
![Screenshot 2019-11-13 at 18 13 52](https://user-images.githubusercontent.com/2409424/68782072-6bd54000-0641-11ea-8ec6-58f595bd70ff.png)

Params for  GTLRYouTube_LiveBroadcast:contentDetails
  GTLRYouTube_LiveBroadcastContentDetails:projection = kGTLRYouTube_LiveBroadcastContentDetails_Projection_X360 GTLRYouTube_LiveBroadcastContentDetails:stereoLayout = kGTLRYouTube_LiveBroadcastContentDetails_StereoLayout_LeftRight

What wrong?

**Comment by thomasvl** [comment]
Since this library generates ObjC wrappers for 100+ apis, we really don't have direct knowledge about all of the apis supported.  Your best bet is to use the support area for the [youtube api](https://developers.google.com/youtube/v3/support).  Since folks there might not know the ObjC api, using the [built in logging support](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) can help provide dumps of the individual REST requests to show what you are sending and getting back.

**Comment by vasilok** [comment]
thanks,  i'll try
