### ISSUE TITLE
Property pageSize doesn't effect the number of search results.

### ISSUE THREAD

**Issue by DimonDeveloper** [google/google-api-objectivec-client-for-rest#327]
I have account with many files in Google Drive.
Search response has more than 3K files, but **pageSize** is equal to 1000.
Any other pageSizes doesn't have effect too.

You can test it in your **DriveSample**.
Add this lines of code to **fetchFileList** method. 
```
query.pageSize = 1000;
query.fields = @"kind,nextPageToken,files(mimeType,id,kind,name,webViewLink,thumbnailLink,trashed)";
query.q = @"trashed = false and name contains '.'";
```

**Update:**
I found out the problem, the library itself processes all **nextPageToken's** and returns all of the files at the same time. To disable it, we need to set **GTLRServiceExecutionParameters** for **GTLRDriveQuery_FilesList** with **shouldFetchNextPages = false**

**Comment by thomasvl** [comment]
From the sounds of things, this is specific to the server in question. Since the library can be used with any service that provides a discovery document, we aren't really experts on any of the apis, so your best bet it to look at the documentation for the api in question ([Drive in this case](https://developers.google.com/drive/api/v3/support)), and see what they suggest for support/questions.  For posting questions, the library supports [logging of the outgoing requests and responses](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic), including those snippets to show the specific request can sometimes help.

**Comment by thomasvl** [comment]
Closing this out since it seems to be a specific server not honoring things and not something we can do anything about within this library.
