### ISSUE TITLE
[GTLRService responsePartWithMIMEPart:] sets error for "204 No Content" responses

### ISSUE THREAD

**Issue by jgheab** [google/google-api-objectivec-client-for-rest#346]
Repro steps:
1. Call [GTLRService responsePartWithMIMEPart:] passing a GTMMIMEDocumentPart instance where the `body` property is set to:

HTTP/1.1 204 No Content
ETag: "<etag>"
Date: <date>
<CRLFCRLF (must end in "\r\n\r\n" with no additional data)>

Expected:
The returned GTLRBatchResponsePart instance should not have its `parseError` or `JSON` properties set, since no error occurred and no content was returned.

Actual:
 `parseError` is set. 
Domain: "com.google.GTLRServiceDomain" (kGTLRServiceErrorDomain).
Code: -3001 (GTLRServiceErrorBatchResponseUnexpected).

**Comment by thomasvl** [comment]
Can you provide some more details?  Normally there are also headers on the mime part which would include a _Content-ID_, etc.  It helps to know we're looking at the same setup.

**Comment by thomasvl** [comment]
If my guess is correct, a little more about what is happening in this batch might help.  I'm guessing you are making multiple request, and one part is succeeding, but with no new content (because of the ETag)?  So this this likely isn't just about this parse being correct, but also ensuring everything else "works" in the case for the batch.

**Comment by Rudal1991** [comment]
http://www.github.com/)
