### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by vheneraliuk** [google/google-api-objectivec-client-for-rest#390]
Do you have any release roadmap or schedule?
Need some changes which weren't released yet and wanted to know how long we need to wait.
Sorry if it's the wrong place for such questions.

**Comment by thomasvl** [comment]
Sorry, nothing set, I try to do semi regular releases.  There's been some hiccups on the discovery documents being served, so  I haven't been able to regenerate lately, let me check in on those, and I'll look to see if we can do a release of atleast the other updated services.

ps - which service are you look for updates too (since those are the only unreleased changes)

**Comment by vheneraliuk** [comment]
I'm interested in the People API service where a few new REST methods were added: https://github.com/google/google-api-objectivec-client-for-rest/commit/0a2950975a0add3764d2b1b6c5b3a84f66551d17#diff-5289b519d60d8bfd3f50f7efcc5574fc

**Comment by thomasvl** [comment]
1.4.3 should be live now.

**Comment by vheneraliuk** [comment]
Thanks!
