### ISSUE TITLE
API URL looks incorrect.

### ISSUE THREAD

**Issue by NSRover** [google/google-api-objectivec-client-for-rest#393]
I am trying to make a Get Spreadsheet call using:

```swift
let sheetconcretequery = GTLRSheetsQuery_SpreadsheetsGet.query(withSpreadsheetId: "11OcMaeLLNYahM0dH3fqZtMybRf6MekHpp4I2hYaUeHo")
sheetconcretequery.includeGridData = true
self.service.executeQuery(sheetconcretequery) { (ticket, results, error) in
    print(error)
}
```

In response I get a 404 - Not found error. I have checked the spreadsheet id in browser and i got it from GTLRDrive's get files call. When I check the network activity i see that call is made to a url with v3/v4/.. I suspect this might be an issue with the library?

`https://www.googleapis.com/drive/v3/v4/spreadsheets/11OcMaeLLNYahM0dH3fqZtMybRf6MekHpp4I2hYaUeHo?includeGridData=true&prettyPrint=false`

**Comment by thomasvl** [comment]
There's isn't really enough here to go on.  The url is built based on the data in the service and the query.  In this case:

https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Sheets/GTLRSheetsService.m#L32

```
    self.rootURLString = @"https://sheets.googleapis.com/";
```

https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Sheets/GTLRSheetsQuery.m#L172

```
  NSString *pathURITemplate = @"v4/spreadsheets/{spreadsheetId}";
```

From the URL you quoted:

> ```
> https://www.googleapis.com/drive/v3/v4/spreadsheets/11OcMaeLLNYahM0dH3fqZtMybRf6MekHpp4I2hYaUeHo?includeGridData=true&prettyPrint=false
> ```

It sorta sounds like your Service (`self.service`) might have had an explicit override applied to the root URL, and that's why things aren't coming out correctly.
