### ISSUE TITLE
How to Accessing Drive Using Service Account

### ISSUE THREAD

**Issue by DSaurabh** [google/google-api-objectivec-client-for-rest#442]
Since GTMAppAuth app auth doesn't support authorisation with a Service Account. 
How i can use drive without user user consent using Service account.
Can u please add example for Drive access using service account.

GTMAppAuth Ticket:
https://github.com/google/GTMAppAuth/issues/46
https://github.com/google/GTMAppAuth/issues/11

**Comment by thomasvl** [comment]
We don't normally talk about service accounts for software that is installed on consumer devices.  Since the service account has to manage the credentials, they are inherently at risk when they are on a consumer device.  Service accounts are more used on a server, where the running space is secured and said credentials aren't as vulnerable.  If you really want to go the service account route, you'll need to look at the general docs on the drive api and Google's docs on service account usage.
