### ISSUE TITLE
[Gmail API] Gmail send api is failing with error 404

### ISSUE THREAD

**Issue by DSaurabh** [google/google-api-objectivec-client-for-rest#458]
When i am sending mail i am getting error 404 "Not Found". how to resolve this issue.
Below is the code snippet and error message for sending mail.
Same app is using google drive which is working fine.

Error Msg:
Printing description of callbackError:
Error Domain=com.google.HTTPStatus Code=404 "Not Found" UserInfo={NSLocalizedDescription=Not Found}

Sample Code:
//Scope Added
    [GIDSignIn sharedInstance].scopes = @[kGTLRAuthScopeDriveFile,kGTLRAuthScopeGmailSend,kGTLRAuthScopeGmailAddonsCurrentActionCompose];
    [[GIDSignIn sharedInstance] signIn];

//Send Message
    NSString *messageString =                              @"From: <sender mail ID>\r\n";
    messageString = [messageString stringByAppendingString:@"To: <recipient mail ID>\r\n"];
    messageString = [messageString stringByAppendingString:@"Subject: Test Mail\r\n"];
    messageString = [messageString stringByAppendingString:@"Content-type: text/html;charset=iso-8859-1\r\n\r\n"];
    messageString = [messageString stringByAppendingString:@"mail Body"];
    
    NSData *data = [messageString dataUsingEncoding:NSUTF8StringEncoding];
    NSString *base64Encoded = GTLREncodeWebSafeBase64(data);
        
    GTLRGmail_Message *message = [[GTLRGmail_Message alloc] init];
    
    message.raw = base64Encoded;
    NSString *userID = GDriveHelper.sharedInstance.googleUser.profile.email;//Sender mail ID
        
    GTLRGmailQuery_UsersMessagesSend *query = [GTLRGmailQuery_UsersMessagesSend queryWithObject:message userId:userID uploadParameters:nil];
    GTLRGmailService *service = (GTLRGmailService*)GDriveHelper.sharedInstance.googleService ;
    [service executeQuery:query completionHandler:^(GTLRServiceTicket * _Nonnull callbackTicket, id  _Nullable object, NSError * _Nullable callbackError) {
        NSLog(@"%@",callbackError);
    }];

**Comment by thomasvl** [comment]
What type of GTLService are you using for `GDriveHelper.sharedInstance.googleService`?  Is that really a GMail one or are you just typecasing a Drive one to GMail so it isn't the right object type?

To help debug things, it helps to enable the logging within the library (https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic), that way you have something that can be used on the api specific help areas.  Since this library generates for 100+ services, we aren't experts on them all, so you might need to use the log and reach out on the api specific area for help.
