### ISSUE TITLE
Cannot debug in lldb

### ISSUE THREAD

**Issue by mkassoff** [google/google-api-objectivec-client-for-rest#478]
After upgrading to any version higher than 1.3.11, we are unable to use lldb in Xcode to debug. Unlike https://github.com/google/google-api-objectivec-client-for-rest/issues/388, we do not see any errors in the console. An example of the failures we get in lldb is shown below.

<img width="846" alt="Screen Shot 2021-09-30 at 12 26 11 PM" src="https://user-images.githubusercontent.com/789728/135518116-4527aa10-c77f-4f8f-ab0c-d108340dddaa.png">

We are using CocoaPods to install the library. In case it is relevant, we also install GTMAppAuth and Firebase via CocoaPods.

**Comment by bezigon** [comment]
I am also facing the same issue.

**Comment by bezigon** [comment]
```
#import "GoogleAPIClientForREST-umbrella.h"
        ^

/Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GoogleAPIClientForREST-umbrella.h:28:9: note: in file included from /Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GoogleAPIClientForREST-umbrella.h:28:
#import "GTLRDrive.h"
        ^

/Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GTLRDrive.h:12:9: note: in file included from /Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GTLRDrive.h:12:
#import "GTLRDriveObjects.h"
        ^

error: /Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GTLRDriveObjects.h:13:11: error: module 'GoogleAPIClientForRESTCore' not found
  @import GoogleAPIClientForRESTCore;
          ^

error: could not build Objective-C module 'GoogleAPIClientForREST'

 SwiftASTContext("Equalizer")::CreateInstance((Module*)0x7fb0dd8b5fa8, "Equalizer") = 0x7fafffec39d0
 SwiftASTContext("Equalizer")::() -- Failed to create module context - <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "GoogleAPIClientForREST-umbrella.h"
        ^

/Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GoogleAPIClientForREST-umbrella.h:28:9: note: in file included from /Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GoogleAPIClientForREST-umbrella.h:28:
#import "GTLRDrive.h"
        ^

/Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GTLRDrive.h:12:9: note: in file included from /Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GTLRDrive.h:12:
#import "GTLRDriveObjects.h"
        ^

error: /Users/bezigon/Documents/Azure/Equalizer-iOS/Pods/Headers/Public/GoogleAPIClientForREST/GTLRDriveObjects.h:13:11: error: module 'GoogleAPIClientForRESTCore' not found
  @import GoogleAPIClientForRESTCore;
          ^

error: could not build Objective-C module 'GoogleAPIClientForREST'

```

**Comment by solariserj** [comment]
Temporally solution I use '~> 1.3.11' for Debug,  but 1.6 in Production

**Comment by bezigon** [comment]
@thomasvl it's hard for me to explain this, but when we found the debug was missing, we decided to find the root of the problem, and found out that this was happening just when the SPM was added.
We remove SPM, there is a debug. We thought the problem was SPM.

BUT, for the purity of the experiment, we created a project from scratch, added SPM, there is a debug. What the hell, I thought.
I add Podfile, there is a debug.
I add Bridging Headers, there is a debug.
Crap.

Okay, back to the original project, with a problem. I decide to find out what exactly the problem is. I connected a script in .llvminit to log the debugger's work. Left SPM unchanged in the project.
I see the compiler swears at headers in Bridging Headers. I remove them completely, no debug.
Heck.

Once again I look at the logs, I see that the compiler is already cursing at the headers GoogleAPIClientForREST.
Hmm, strange. I decide to comment them out in the Podfile. And ... voila! Debug appeared!

I start googling, I find this Issue exactly the same as my problem.
We now realize that this is due to the rare configuration of the project, the phases of the moon, and a little bit of heck.

The same for Russian readers: 

@thomasvl мне сложно объяснить, но когда мы обнаружили пропажу дебага, мы решили найти корень проблемы, и выяснили, что это происходило как раз при добавлении SPM.
Убираем SPM, есть дебаг. Думали, что проблема в SPM.

НО, для чистоты эксперимента, мы создали проект с нуля, добавили SPM, есть дебаг. Что за чертовщина, подумал я.
Добавляю Podfile, есть дебаг.
Добавляю Bridging Headers, есть дебаг.
Блин.

Ладно, возвращаюсь к оригинальному проекту, с проблемой. Решаю выяснить, в чем же конкретно проблема. Подключил скрипт в .llvminit  для логирования работы дебаггера. Оставил SPM.
Смотрю, ругается на хедеры в Bridging Headers, удаляю их полностью, нет дебага.
Еще раз смотрю на логи, вижу, ругается уже на хедеры GoogleAPIClientForREST.
Хм, странно. Решаю их закомментировать в Podfile. И... вуаля! появился дебаг!

Начинаю гуглить, нахожу этот Issue с точь в точь с моей проблемой.
Теперь мы понимаем, что это дело в редкой конфигурации проекта, фаз луны, и немного чертовщины.

**Comment by thomasvl** [comment]
@bezigon that sounds like it is specific to SwiftPM which is different than the initial report where it was just about updated the CocoaPod.  SwiftPM issues are tracked in #400

**Comment by mkassoff** [comment]
@thomasvl I did some further testing and found that, in a clean project, I am able to debug in lldb without issue using 1.6.0, but after adding in all of the files in our project (and SPM imports), lldb breaks. So yes, these is clearly something else in my project that, in combination with GoogleAPIClientForREST, causes the issue. I am not clear what it is, yet. It does sound like we are not the only ones facing the issue (see @solariserj's comment above).

**Comment by thomasvl** [comment]
Since you're using a mix of package manages, that makes some sense that that's tripping things up.  At the moment, the current sources assume if `SWIFT_PACKAGE` is defined, you are SwiftPM for importing the package.

**Comment by LucaComanducci** [comment]
I am also facing this issue.

I've added 'GoogleAPIClientForREST/Drive' with Cocoapod to my project: the "@Import GoogleAPIClientForREST" with at least one Swift Package installed broke the Xcode debugger and cause the "cannot find -variable- in scope" error.

Installing the pod with '~> 1.3.11' is a good workaround for now. I hope someone can find the root of the problem soon and release a fix for the latest version.

**Comment by thomasvl** [comment]
We just did a 2.0 release where we changed the project layout to use the same sorta layout that Firebase, etc. do, so hopefully this will solve these build related issues for folks.
