### ISSUE TITLE
Documentation on changes with 2.0.0

### ISSUE THREAD

**Issue by strongbox-mark** [google/google-api-objectivec-client-for-rest#551]
Hi there, we use this library via Cocoapods in our App. We just ran a 'pod update' and got bumped from 1.7.0 to 2.0.0. We've got some issues with compilation which means we will rollback for now, but we'd obviously like to upgrade to 2.0.0. 

We were looking for any documentation on what's changed with 2.0.0 but have come up empty. Is there a migration guide for users who were on 1.7.0? Is there any kind of brief description of the philosophy behind the major version update we could read about?

We've just hit a bit of a wall here, we're hoping this won't require major changes on our side, but we haven't received any kind of notification about the changes. Perhaps @thomasvl, you could help?

Also, what kind of deprecation timeline are we looking at for 1.7.0 so that we can plan? 

If there's a better place to raise these issues, please let us know. Thanks! :)

**Comment by thomasvl** [comment]
The releases page has the [notes for this release](https://github.com/google/google-api-objectivec-client-for-rest/releases/tag/v2.0.0).  We did a bunch of layout changes to better support SwiftPM, pruned some legacy things, but no general api changes; so short of maybe some integration tweaks, we weren't expecting major issues with this release. We did the 2.0 version as an added safety net of calling it a major change just incase.  What are the specifics problems you hit?

**Comment by strongbox-mark** [comment]
Hi @thomasvl - Thanks for the extra detail, sounds like we should be able to get this working... 

We got some kind of duplicate include error (GTLR_DriveObject.h) I believe. It could be that we're using an older version of the GoogleSignIn component (   pod 'GoogleSignIn', '5.0.2' ). Do you know if this should still work, or if we would need to upgrade to the latest GoogleSignIn pod to use this? I believe there are quite a few changes to the SignIn component we'd need to work on.

I can come back with more detail if you'd like, we can upgrade to 2.0.0 and send you the compile errors we're seeing if that would be helpful.

**Comment by thomasvl** [comment]
I don't think GoogleSignIn uses GTLR in any way, so that should matter (there is overlap with GTMSessionFetcher, so that might not have been updated to that 2.0 version yet, but that wouldn't impact things related to this project).

One of the things in the release:

>  Prefer imports over fwd decls to avoid potential partial types #538

So that could be coming into play, as the headers now import each other and avoid fwd declarations to Swift can never run into the problem where it drops attributes for things that it is only seen a forward declaration.  But our projects and the examples haven't hit any issues with duplicate definitions.

Yes, posting the errors and some details about how you integrate:
- CocaoPods/SwiftPM
- Is your code ObjC or Swift?
- If ObjC do you do module imports or header imports?

Another option is if you can make a small sample project that shows the problem will likely help figure out what's going on.
