### ISSUE TITLE
in iOS, how to directly download the content of a shareable link

### ISSUE THREAD

**Issue by wangbourne** [google/google-api-objectivec-client-for-rest#65]
For example, I got a shareable link, which is targeted at a zip file on Google Drive from other people.    On the web, click the shareable link, I will get a web page, via which I can download it from the linkage.  Can I directly download it in my iOS app, rather than redirect to a webpage first?

This link provides a way to do this: http://webapps.stackexchange.com/questions/30654/in-google-drive-how-can-you-link-directly-to-download-a-zip-file-and-not-view/30656#30656?newreg=ac981950d09348699d379b0587d262b4. However, i would like to see an official way :)

Thanks

**Comment by thomasvl** [comment]
Since the sdk covers lots of APIs we aren't always the exports on all of them, so you want to check the general [api docs](https://developers.google.com/drive/v3/reference/), they also have a "Support" tab with where the server folks can be contacted for questions.

Sounds like you are after export: https://developers.google.com/drive/v3/reference/files/export, which generates at https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Drive/GTLRDriveQuery.h#L690-L725

**Comment by wangbourne** [comment]
yes, you are right. I can get shareable link from the field of webContentLink and then download it.
